repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: mixed-line-ending
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pycqa/doc8
    rev: 0.11.1
    hooks:
    -   id: doc8
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/adamchainz/django-upgrade
    rev: 1.5.0
    hooks:
    -   id: django-upgrade
        args: [--target-version, "3.2"]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
    -   id: python-check-blanket-noqa
    -   id: python-check-mock-methods
    -   id: python-no-eval
    -   id: python-no-log-warn
    -   id: rst-backticks
    -   id: rst-directive-colons
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
    -   id: prettier
        types_or: [javascript, css]
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.13.0
    hooks:
    -   id: eslint
        files: \.js?$
        types: [file]
        args:
        - --fix
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3
        entry: black --target-version=py37
