language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - env: TOXENV=flake8
    - env: TOXENV=style
    - env: TOXENV=readme
    - python: 3.5
      env: TOXENV=py35-dj111
    - python: 3.6
      env: TOXENV=py36-dj111
    - python: 3.7
      env: TOXENV=py37-dj111
    - python: 3.5
      env: TOXENV=py35-dj22
    - python: 3.6
      env: TOXENV=py36-dj22
    - python: 3.7
      env: TOXENV=py37-dj22
    - python: 3.8
      env: TOXENV=py38-dj22
    - python: 3.6
      env: TOXENV=py36-dj30
    - python: 3.7
      env: TOXENV=py37-dj30
    - python: 3.8
      env: TOXENV=py38-dj30
    - python: 3.6
      env: TOXENV=py36-djmaster
    - python: 3.7
      env: TOXENV=py37-djmaster
    - python: 3.8
      env: TOXENV=py38-djmaster
    - env: TOXENV=postgresql
      addons:
        postgresql: "9.5"
    - env: TOXENV=mariadb
      addons:
        mariadb: "10.3"
      script:
        # working around https://travis-ci.community/t/mariadb-build-error-with-xenial/3160
        - mysql -u root -e "DROP USER IF EXISTS 'travis'@'%';"
        - mysql -u root -e "CREATE USER 'travis'@'%';"
        - mysql -u root -e "CREATE DATABASE debug_toolbar;"
        - mysql -u root -e "GRANT ALL PRIVILEGES ON *.* TO 'travis'@'%';";
        - tox -v
  allow_failures:
    - env: TOXENV=py36-djmaster
    - env: TOXENV=py37-djmaster
    - env: TOXENV=py38-djmaster

install:
  - pip install tox codecov
script:
  - tox -v
after_success:
  - codecov
