dist: xenial
sudo: false
language: python
cache: pip
matrix:
  fast_finish: true
  include:
    - python: 2.7
    - python: 3.4
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: 3.7
      env: TOXENV=postgresql
      addons:
        postgresql: "9.5"
    - python: 3.7
      env: TOXENV=mariadb
      addons:
        mariadb: "10.3"
    - env: TOXENV=flake8
    - python: 3.7
      env: TOXENV=style
    - python: 3.7
      env: TOXENV=readme

install:
  - pip install tox tox-travis codecov
script:
  - tox -v
after_success:
  - codecov
